source "https://rubygems.org"

# This gem allows your local environment to mimic GitHub Pages
gem "github-pages", group: :jekyll_plugins

# Lanyon specifically requires pagination to work correctly
gem "jekyll-paginate"
